name: Build Python Script

on: [push, pull_request]

jobs:
  build_linux:
    name: Build Executable
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile dump-helper.py
        cp third-party/x86_64/linux/* dist/ -rf

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dump-helper-x86_64-windows.zip
        path: dist/*

  build_windows:
    name: Build Executable for Windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 指定具体的Python 3版本，如3.8或3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile dump-helper.py
        cp third-party/x86_64/win32/* dist/ -rf

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dump-helper-x86_64-linux.tar.xz
        path: dist/*

  build_mac:
    name: Build Executable for Mac
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 指定具体的Python 3版本，如3.8或3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile dump-helper.py
        cp third-party/x86_64/darwin/* dist/ -rf

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dump-helper-x86_64-apple-darwin.tar.xz
        path: dist/*