name: Build Python Script

on: [push, pull_request]

jobs:
  build_linux:
    name: Build Executable for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller dump-helper.linux.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dump-helper-x86_64-linux
        path: dist/*

  build_windows:
    name: Build Executable for Windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller dump-helper.win32.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dump-helper-x86_64-windows.exe
        path: dist/*

  build_mac:
    name: Build Executable for Mac
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller dump-helper.darwin.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dump-helper-x86_64-apple-darwin
        path: dist/*